stages:
  - dependabot
  - test

dependabot:
  image: ghcr.io/dependabot-gitlab/dependabot:latest
  stage: dependabot
  variables:
    GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN
    PROJECT: $CI_PROJECT_PATH
    PACKAGE_MANAGER: "bun"
    DIRECTORY: "/"
    BRANCH: $CI_DEFAULT_BRANCH
    AUTO_MERGE: "false"
  script:
    - bundle exec ruby /app/dependabot.rb
  only:
    - schedules # Run only on scheduled pipelines

test:
  stage: test
  image: oven/bun:latest
  timeout: 60m
  before_script:
    - echo "Install Playwright"
    - bunx playwright install --with-deps
    - echo "Install dependencies"
    - bun install
  script:
    - echo "Run Playwright tests"
    - bun run test:headless
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 30 days
